name: 'gh2rdf'
description: 'Github to RDF'
inputs:
  owner:
    description: 'Owner'
    required: true
  repo:
    description: 'Repository name'
    required: false
  type:
    description: 'Issues or pull-requests'
    required: false
  org:
    description: 'If type of pull-requests is set then the organization to limit the collecting too'
    required: false
  output:
    description: 'Output file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.type }}
    - ${{ inputs.org }}
    - ${{ inputs.output }}